version: '2'
services:
  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Paris
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app:cached
    working_dir: /var/www/app

  webserver:
    image: nginx:1.12-alpine
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: keyley_test
      MYSQL_USER: keyley
      MYSQL_PASSWORD: keyley_password
    volumes:
     - data:/var/lib/mysql

volumes:
  data:
    driver: "local"
